service: scrapped
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  profile: default
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:ap-northeast-2:474083796669:table/goodoc-untact-scrapper-scrapped"

functions:
  scrapped:
    handler: src/index.scrapped
    events: 
      - http:
          path: scrapped/{selectorId}
          method: get
plugins:
  - serverless-offline
  - serverless-plugin-typescript